/*
 * player.js — runtime for a narrated motion-design video that plays in the browser.
 *
 * Model: everything on the stage is a pure function of the playhead `t` (seconds).
 *   - one paused GSAP master timeline, set to `t` every frame
 *   - onFrame(fn) hooks, called with `t` every frame (canvas, counters, procedural motion)
 *   - CSS/WAAPI animations inside the stage, paused and set to `t` every frame
 * While narration is playing, the audio element is the clock and visuals follow it,
 * so sync holds during real-time playback (and screen recording) and seeking works.
 *
 * Normally you do not edit this file. Author the video in js/scenes.js via Video.define().
 */
(function () {
  'use strict';

  const DATA = window.VIDEO_DATA || null;
  const params = new URLSearchParams(location.search);
  const stage = document.getElementById('stage');
  const W = Number(stage.dataset.width) || 1920;
  const H = Number(stage.dataset.height) || 1080;
  stage.style.width = W + 'px';
  stage.style.height = H + 'px';
  const lang = (DATA && DATA.lang) || document.documentElement.lang || 'ko';
  const TXT = {
    ko: { play: '전체화면으로 재생', window: '창에서 재생', loading: '불러오는 중…',
          hint: 'Space 재생/일시정지 · ←/→ 5초 이동 · F 전체화면 · C 자막 · D 디버그 · R 처음부터',
          placeholder: '임시(무음) 내레이션 — 실제 음성이 아닙니다' },
    en: { play: 'Play fullscreen', window: 'Play in window', loading: 'Loading…',
          hint: 'Space play/pause · ←/→ seek 5s · F fullscreen · C captions · D debug · R restart',
          placeholder: 'Placeholder (silent) narration — not the real voice' },
  }[lang.startsWith('ko') ? 'ko' : 'en'];

  // ---------- state ----------
  let builder = null;
  let tl = null;
  const frameFns = [];
  const canvases = [];
  let t = 0;
  let duration = 0;
  let playing = false;
  let audioStarting = false;
  let anchorT = 0;
  let anchorPerf = 0;
  let scale = 1;
  const audioDur = DATA ? DATA.audioDuration : 0;
  const audio = new Audio();
  let audioOk = !!(DATA && DATA.audio);
  audio.preload = 'auto';
  audio.addEventListener('error', () => {
    audioOk = false;
    console.error('[video] narration failed to load:', DATA && DATA.audio);
  });
  if (audioOk) audio.src = DATA.audio;

  const now = () => performance.now() / 1000;
  const clamp = (v, a, b) => Math.min(b, Math.max(a, v));

  // ---------- public authoring API ----------
  const Video = {
    define(fn) { builder = fn; },
    get time() { return t; },
    get duration() { return duration; },
    play: () => play(),
    pause: () => pause(),
    seek: (x) => seek(x),
  };
  window.Video = Video;
  window.__video = Video; // handy in the console

  function makeCue(c) {
    const text = c.text || '';
    const weight = (s) => s.replace(/[\s.,!?·…"'“”‘’()\[\]-]/g, '').length;
    const total = Math.max(1, weight(text));
    return Object.freeze({
      ...c,
      /** time at a fraction (0..1) of this cue's spoken duration */
      at: (f) => c.start + clamp(f, 0, 1) * c.duration,
      /** estimated time a phrase is spoken, by its character position in the cue text */
      when(phrase, offset = 0) {
        const i = text.indexOf(phrase);
        if (i < 0) {
          console.warn(`[video] cue "${c.id}": phrase not found: "${phrase}"`);
          return c.start + offset;
        }
        return c.start + c.duration * (weight(text.slice(0, i)) / total) + offset;
      },
    });
  }

  function buildContext() {
    const cueList = DATA.cues.map(makeCue);
    const byId = new Map(cueList.map((c) => [c.id, c]));
    tl = gsap.timeline({ paused: true });
    for (const c of cueList) {
      tl.addLabel(c.id, c.start);
      tl.addLabel(c.id + '_end', c.end);
    }
    return {
      tl,
      gsap,
      stage,
      W,
      H,
      data: DATA,
      cues: cueList,
      cue(id) {
        const c = byId.get(id);
        if (!c) throw new Error(`[video] unknown cue id "${id}". Known: ${[...byId.keys()].join(', ')}`);
        return c;
      },
      /** show `target` only between `from` and `to` (seconds). Uses visibility, so CSS animations keep running. */
      scene(target, from, to) {
        const el = typeof target === 'string' ? stage.querySelector(target) : target;
        if (!el) throw new Error(`[video] scene target not found: ${target}`);
        gsap.set(el, { autoAlpha: 0 });
        tl.set(el, { autoAlpha: 1 }, from);
        if (to != null) tl.set(el, { autoAlpha: 0 }, to);
        return el;
      },
      onFrame(fn) { frameFns.push(fn); },
      /** deterministic PRNG (mulberry32). Same seed → same sequence, every run. */
      rand(seed = 1) {
        let a = seed >>> 0;
        return () => {
          a = (a + 0x6d2b79f5) >>> 0;
          let r = Math.imul(a ^ (a >>> 15), 1 | a);
          r = (r + Math.imul(r ^ (r >>> 7), 61 | r)) ^ r;
          return ((r ^ (r >>> 14)) >>> 0) / 4294967296;
        };
      },
      /** size a <canvas> for crisp drawing in stage coordinates; returns its 2D context */
      fitCanvas(canvas, w = W, h = H) {
        const entry = { canvas, w, h, ctx: canvas.getContext('2d') };
        canvases.push(entry);
        sizeCanvas(entry);
        return entry.ctx;
      },
    };
  }

  function sizeCanvas(e) {
    const ratio = Math.min(3, Math.max(1, scale * (window.devicePixelRatio || 1)));
    e.canvas.width = Math.round(e.w * ratio);
    e.canvas.height = Math.round(e.h * ratio);
    e.canvas.style.width = e.w + 'px';
    e.canvas.style.height = e.h + 'px';
    e.ctx.setTransform(ratio, 0, 0, ratio, 0, 0);
  }

  // ---------- layout ----------
  function fit() {
    scale = Math.min(innerWidth / W, innerHeight / H);
    stage.style.transform = `translate(-50%, -50%) scale(${scale})`;
    for (const e of canvases) sizeCanvas(e);
    if (tl) render();
  }

  // ---------- rendering ----------
  function render() {
    // never sit exactly on 0: GSAP skips zero-duration sets placed at 0 until the playhead moves past them
    tl.time(clamp(t, 1e-4, tl.duration()), false);
    for (const fn of frameFns) fn(t);
    const ms = t * 1000;
    const anims = document.getAnimations ? document.getAnimations() : [];
    for (const a of anims) {
      const target = a.effect && a.effect.target;
      if (!target || !stage.contains(target)) continue;
      if (a.playState !== 'paused') a.pause();
      a.currentTime = ms;
    }
    ui.update();
  }

  // ---------- clock ----------
  function tick() {
    if (playing && !audioStarting) {
      let next = anchorT + (now() - anchorPerf);
      if (audioOk && next < audioDur && !audio.paused && !audio.seeking) {
        const drift = audio.currentTime - next;
        if (Math.abs(drift) > 0.25) { anchorT = audio.currentTime; anchorPerf = now(); next = anchorT; }
        else if (Math.abs(drift) > 0.015) { anchorT += drift * 0.1; next += drift * 0.1; }
      }
      if (next >= duration) {
        next = duration;
        playing = false;
        audio.pause();
        document.body.classList.remove('vp-playing');
        document.body.classList.add('vp-ended');
      }
      t = next;
      render();
    }
    requestAnimationFrame(tick);
  }

  async function play() {
    if (playing || audioStarting) return;
    if (t >= duration - 1e-3) t = 0;
    document.body.classList.remove('vp-ended');
    if (t < audioDur && audioOk) {
      audioStarting = true;
      audio.currentTime = t;
      try {
        await audio.play();
        anchorT = audio.currentTime;
      } catch (err) {
        if (err && err.name === 'NotAllowedError') {
          audioStarting = false;
          console.warn('[video] autoplay blocked; waiting for a click.');
          ui.showStart();
          return;
        }
        console.error('[video] narration cannot play; continuing silently.', err);
        anchorT = t;
      }
      audioStarting = false;
    } else {
      anchorT = t;
    }
    anchorPerf = now();
    playing = true;
    document.body.classList.add('vp-playing');
  }

  function pause() {
    playing = false;
    audio.pause();
    document.body.classList.remove('vp-playing');
    render();
  }

  function seek(x) {
    t = clamp(x, 0, duration);
    document.body.classList.toggle('vp-ended', t >= duration);
    if (playing) {
      anchorT = t;
      anchorPerf = now();
      if (t < audioDur && audioOk) {
        audio.currentTime = t;
        if (audio.paused) audio.play().catch(() => {});
      } else {
        audio.pause();
      }
    }
    render();
  }

  // ---------- UI (lives outside the stage, never recorded unless shown) ----------
  const ui = (() => {
    const el = (tag, cls, parent = document.body) => {
      const n = document.createElement(tag);
      if (cls) n.className = cls;
      parent.appendChild(n);
      return n;
    };
    const start = el('div', 'vp-start');
    const title = el('div', 'vp-start-title', start);
    const buttons = el('div', 'vp-start-buttons', start);
    const btnFs = el('button', 'vp-btn vp-btn-primary', buttons);
    const btnWin = el('button', 'vp-btn', buttons);
    const hint = el('div', 'vp-start-hint', start);
    const warn = el('div', 'vp-start-warn', start);
    btnFs.textContent = '▶ ' + TXT.play;
    btnWin.textContent = TXT.window;
    hint.textContent = TXT.hint;
    title.textContent = TXT.loading;
    btnFs.disabled = btnWin.disabled = true;

    const captions = el('div', 'vp-captions', stage);
    const debug = el('div', 'vp-debug');
    const dbgInfo = el('div', 'vp-debug-info', debug);
    const bar = el('div', 'vp-debug-bar', debug);
    const fill = el('div', 'vp-debug-fill', bar);
    let showCaptions = params.has('captions');
    let showDebug = params.has('debug');
    let lastCue = null;
    let cursorTimer = 0;

    function currentCue() {
      if (!DATA) return null;
      for (const c of DATA.cues) if (t >= c.start && t < c.end) return c;
      return null;
    }
    function fmt(s) {
      const m = Math.floor(s / 60);
      return `${m}:${(s - m * 60).toFixed(2).padStart(5, '0')}`;
    }

    bar.addEventListener('pointerdown', (e) => {
      const r = bar.getBoundingClientRect();
      seek(((e.clientX - r.left) / r.width) * duration);
    });
    document.addEventListener('mousemove', () => {
      document.body.classList.add('vp-cursor');
      clearTimeout(cursorTimer);
      cursorTimer = setTimeout(() => document.body.classList.remove('vp-cursor'), 1500);
    });

    return {
      ready() {
        title.textContent = (DATA && DATA.title) || document.title;
        btnFs.disabled = btnWin.disabled = false;
        if (DATA && DATA.placeholder) warn.textContent = '⚠ ' + TXT.placeholder;
        for (const c of DATA.cues) {
          const m = el('div', 'vp-debug-mark', bar);
          m.style.left = (c.start / duration) * 100 + '%';
          m.style.width = (c.duration / duration) * 100 + '%';
          m.title = `${c.id}: ${c.text}`;
        }
        btnFs.onclick = () => this.startFullscreen();
        btnWin.onclick = () => { this.hideStart(); play(); };
        btnFs.focus();
        this.update();
      },
      async startFullscreen() {
        this.hideStart();
        try { await document.documentElement.requestFullscreen(); } catch (_) { /* not allowed: play in window */ }
        await new Promise((r) => setTimeout(r, 900)); // let the fullscreen transition settle before t=0 moves
        play();
      },
      hideStart() { start.classList.add('vp-hidden'); },
      showStart() { start.classList.remove('vp-hidden'); },
      startVisible() { return !start.classList.contains('vp-hidden'); },
      error(msg) {
        title.textContent = '⚠ ' + msg;
        title.classList.add('vp-error');
        btnFs.disabled = btnWin.disabled = true;
      },
      toggleCaptions() { showCaptions = !showCaptions; lastCue = undefined; this.update(); },
      toggleDebug() { showDebug = !showDebug; this.update(); },
      update() {
        const c = currentCue();
        captions.classList.toggle('vp-on', showCaptions && !!c);
        if (showCaptions && c !== lastCue) {
          captions.textContent = c ? c.text : '';
          lastCue = c;
        }
        debug.classList.toggle('vp-on', showDebug);
        if (showDebug) {
          dbgInfo.textContent = `${fmt(t)} / ${fmt(duration)}   ${c ? `[${c.id}] ${c.text}` : ''}`;
          fill.style.width = (duration ? (t / duration) * 100 : 0) + '%';
        }
      },
    };
  })();

  // ---------- keyboard ----------
  document.addEventListener('keydown', (e) => {
    if (e.metaKey || e.ctrlKey || e.altKey) return;
    const k = e.key;
    if (ui.startVisible() && tl) {
      if (k === 'Enter') { e.preventDefault(); ui.startFullscreen(); }
      else if (k === ' ') { e.preventDefault(); ui.hideStart(); play(); }
      return;
    }
    if (!tl) return;
    const step = e.shiftKey ? 1 : 5;
    if (k === ' ') { e.preventDefault(); playing ? pause() : play(); }
    else if (k === 'ArrowRight') seek(t + step);
    else if (k === 'ArrowLeft') seek(t - step);
    else if (k === '.') { if (!playing) seek(t + 1 / 30); }
    else if (k === ',') { if (!playing) seek(t - 1 / 30); }
    else if (k === 'Home' || k === '0') seek(0);
    else if (k === 'r' || k === 'R') { seek(0); play(); }
    else if (k === 'f' || k === 'F') {
      if (document.fullscreenElement) document.exitFullscreen();
      else document.documentElement.requestFullscreen().catch(() => {});
    }
    else if (k === 'c' || k === 'C') ui.toggleCaptions();
    else if (k === 'd' || k === 'D') ui.toggleDebug();
  });

  // ---------- boot ----------
  async function boot() {
    fit();
    addEventListener('resize', fit);
    document.addEventListener('fullscreenchange', fit);

    if (!DATA) return ui.error('js/cues.js is missing — run scripts/tts.mjs first.');
    if (typeof gsap === 'undefined') return ui.error('GSAP failed to load (vendor/gsap/gsap.min.js).');
    const plugins = ['SplitText', 'CustomEase', 'CustomBounce', 'CustomWiggle', 'DrawSVGPlugin',
      'MorphSVGPlugin', 'MotionPathPlugin', 'TextPlugin', 'ScrambleTextPlugin'];
    gsap.registerPlugin(...plugins.map((p) => window[p]).filter(Boolean));

    // Fonts must be ready before anything measures text (SplitText, layout-dependent tweens).
    const waitAudio = new Promise((res) => {
      if (!audioOk || audio.readyState >= 3) return res();
      audio.addEventListener('canplaythrough', res, { once: true });
      audio.addEventListener('error', res, { once: true });
      setTimeout(res, 5000);
    });
    await Promise.all([document.fonts ? document.fonts.ready : null, waitAudio]);

    if (!builder) return ui.error('js/scenes.js did not call Video.define().');
    try {
      await builder(buildContext());
    } catch (err) {
      console.error(err);
      return ui.error('scenes.js error: ' + (err && err.message ? err.message : err));
    }
    duration = Math.max(DATA.duration || 0, tl.duration());
    t = clamp(Number(params.get('t')) || 0, 0, duration);
    render();
    ui.ready();
    document.body.classList.add('vp-ready');
    requestAnimationFrame(tick);
  }

  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', boot);
  else setTimeout(boot, 0); // let scenes.js (loaded after this file) call Video.define first
})();
